### ISSUE TITLE
[EPIC] parser

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/UNICT-Elezioni#18]
-  [x]  fare in modo che l'attuale parser converta tutti i dati dei risultati dell'anno 2018-2020 PDF -> JSON, estraendo più dati possibili
-  [x] https://github.com/UNICT-DMI/UNICT-Elezioni/issues/3
-  [x] https://github.com/UNICT-DMI/UNICT-Elezioni/issues/13

---
-  [x] fare in modo che il parser sia compatibile con i PDF 2016-2018
-  [x] https://github.com/UNICT-DMI/UNICT-Elezioni/issues/15
---
- estrarre i dati antecedenti al 2016 (questo diciamo che per ora è facoltativo e non è detto che sia fattibile)
- ~https://github.com/UNICT-DMI/UNICT-Elezioni/issues/16~
- ~https://github.com/UNICT-DMI/UNICT-Elezioni/issues/17~
